# Generated by Django 3.2.7 on 2021-10-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=20)),
                ('vechileSegment', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='premium',
            fields=[
                ('premiumID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateOfPurchage', models.DateField()),
                ('premiumAmount', models.IntegerField()),
                ('bodyInjuryLiability', models.IntegerField()),
                ('personalInjuryProtection', models.IntegerField()),
                ('propertyDamageLiability', models.IntegerField()),
                ('collision', models.IntegerField()),
                ('comprehensive', models.IntegerField()),
                ('customerIncomeGroup', models.CharField(max_length=10)),
                ('customerMaritalStatus', models.IntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='insurence.customer')),
            ],
        ),
    ]
